version: "3"
services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
        - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT=${PORT}
      - DB_URI=${DB_URI}
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
volumes:
  mongodb:
